#!/bin/bash
# Only Plesk Web Host Edition Trial key are availavle since previous change in Plesk Panel licenses
# Following sites update Every 14 Days with new key
# 1] https://trialplesk.domainhizmetleri.com 
#
# 2] https://plesktrial.yoncu.com/
# plesk php -er "eval(file_get_contents('https://plesktrial.yoncu.com/?CMD=x'));";
#
# 3] https://www.dunyaatlasi.com/plesk-trial-lisans-kodu/
#
# *************** do not change below this line ***************
#
key=$(/usr/bin/wget https://gist.githubusercontent.com/yashodhank/a7ac287504b7f6358a9791bc725da973/raw/trial -q -O -)
key_id=$(/usr/sbin/plesk bin keyinfo --list | grep plesk_key_id | grep -Eo '[[:alpha:]]{4}[[:digit:]]{12}')
lim_date=$(/usr/sbin/plesk bin keyinfo --list | grep lim_date | grep -Eo '[[:digit:]]{8}')
# plesk_key_id: plsk000000000000 | lim_date: -1
#if [ "${key_id}" = "plsk000000000000" ] || [ $lim_date -eq -1 ]
#then
/bin/rm -rf /etc/sw/keys/keys/key*
/usr/sbin/plesk bin license -i ${key}
#exit 0
#else
#echo "Error Key Id: ${key_id} OR  Key Date: ${lim_date} exists!";
#exit 113
#fi
